# .pre-commit-config.yaml

---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
        description: Forces to replace line ending by the UNIX "lf" character.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.35.0
    hooks:
      - id: check-metaschema
        files: '.*schema\.json$'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        args: [--config-file=pyproject.toml]
        exclude: alembic/
        additional_dependencies: [
            "pydantic",
            "fastapi",
            "pydantic_settings",
            "dotenv",
            "uvicorn",
            "sqlalchemy",
            "geoalchemy2",
            "shapely",
            "pytest",
            "duckdb",
            "pyarrow",
            "fsspec",
            "requests",
            "country-converter",
            "geopandas",
            "shapely",
        ]
