version: 2.1

workspace: &workspace-dir /tmp/workspace

jobs:
  build:
    working_directory: *workspace-dir
    docker:
      - image: cimg/python:3.12
        user: root
        environment:
          - DB_USER=user
          - DB_PASSWORD=password
          - DB_NAME=postgres
          - DB_PORT=5432
      - image: postgres:15-alpine
        environment:
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=postgres
          - POSTGRES_HOST=localhost
          - POSTGRES_PORT=5432

    steps:
      - attach_workspace:
          at: *workspace-dir
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            poetry config virtualenvs.in-project true && \
            poetry install --no-interaction --no-ansi
      - run:
          name: "Wait for database"
          command: |
            until psql -h localhost -U user -d postgres -c ";"; do
              echo "Waiting for database..."
              sleep 2
            done
      - run:
          name: "Run pre-commit"
          command: |
            poetry run pre-commit run --all-files
      - run:
          name: "Run tests"
          command: |
            poetry run pytest

workflows:
  build-and-test:
    jobs:
      - build
