"""Added building_footprints table

Revision ID: 6205ce21172e
Revises: 1385d54dbf82
Create Date: 2025-11-24 11:33:03.428371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '6205ce21172e'
down_revision: Union[str, Sequence[str], None] = '1385d54dbf82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'building_footprints',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('confidence', sa.Float),
        sa.Column('area_meters', sa.Float),
        sa.Column('geom', Geometry('POLYGON', srid=4326)) 
    )
    op.create_index(
        'idx_buildings_geom', 'building_footprints', ['geom'], postgresql_using='gist'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_buildings_geom', table_name='building_footprints')
    op.drop_table('building_footprints')
    # ### end Alembic commands ###
